config/routes.rb
Rails.application.routes.draw do
  resources :pants
  resources :shirts
  resources :shoes
  resources :stores

end

app/models/pant.rb
class Pant < ActiveRecord::Base
  belongs_to :store

  def attributes
    [:name,:style,:inseam,:waist]
  end
end

app/models/shirt.rb
class Shirt < ActiveRecord::Base
  belongs_to :store

  def attributes
    [:name,:style,:size,:neck]
  end
end

app/models/shoe.rb
class Shoe < ActiveRecord::Base
  belongs_to :store

  def attributes
    [:name,:style,:size,:color]
  end
end

app/models/store.rb
class Store < ActiveRecord::Base
  has_many :pants
  has_many :shirts
  has_many :shoes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pants_controller.rb
class PantsController < ApplicationController
  before_action :set_pant, only: [:show, :edit, :update, :destroy]

  # GET /pants
  # GET /pants.json
  def index
    @pants = Pant.all
  end

  # GET /pants/1
  # GET /pants/1.json
  def show
  end

  # GET /pants/new
  def new
    @pant = Pant.new
  end

  # GET /pants/1/edit
  def edit
  end

  # POST /pants
  # POST /pants.json
  def create
    @pant = Pant.new(pant_params)

    respond_to do |format|
      if @pant.save
        format.html { redirect_to @pant, notice: 'Pant was successfully created.' }
        format.json { render :show, status: :created, location: @pant }
      else
        format.html { render :new }
        format.json { render json: @pant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pants/1
  # PATCH/PUT /pants/1.json
  def update
    respond_to do |format|
      if @pant.update(pant_params)
        format.html { redirect_to @pant, notice: 'Pant was successfully updated.' }
        format.json { render :show, status: :ok, location: @pant }
      else
        format.html { render :edit }
        format.json { render json: @pant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pants/1
  # DELETE /pants/1.json
  def destroy
    @pant.destroy
    respond_to do |format|
      format.html { redirect_to pants_url, notice: 'Pant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pant
      @pant = Pant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pant_params
      params.require(:pant).permit(:name, :style, :inseam, :waist, :img_url, :src_url)
    end
end

app/controllers/shirts_controller.rb
class ShirtsController < ApplicationController
  before_action :set_shirt, only: [:show, :edit, :update, :destroy]

  # GET /shirts
  # GET /shirts.json
  def index
    @shirts = Shirt.all
  end

  # GET /shirts/1
  # GET /shirts/1.json
  def show
  end

  # GET /shirts/new
  def new
    @shirt = Shirt.new
  end

  # GET /shirts/1/edit
  def edit
  end

  # POST /shirts
  # POST /shirts.json
  def create
    @shirt = Shirt.new(shirt_params)

    respond_to do |format|
      if @shirt.save
        format.html { redirect_to @shirt, notice: 'Shirt was successfully created.' }
        format.json { render :show, status: :created, location: @shirt }
      else
        format.html { render :new }
        format.json { render json: @shirt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shirts/1
  # PATCH/PUT /shirts/1.json
  def update
    respond_to do |format|
      if @shirt.update(shirt_params)
        format.html { redirect_to @shirt, notice: 'Shirt was successfully updated.' }
        format.json { render :show, status: :ok, location: @shirt }
      else
        format.html { render :edit }
        format.json { render json: @shirt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shirts/1
  # DELETE /shirts/1.json
  def destroy
    @shirt.destroy
    respond_to do |format|
      format.html { redirect_to shirts_url, notice: 'Shirt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shirt
      @shirt = Shirt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shirt_params
      params.require(:shirt).permit(:name, :style, :size, :neck, :img_url, :src_url)
    end
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  before_action :set_shoe, only: [:show, :edit, :update, :destroy]

  # GET /shoes
  # GET /shoes.json
  def index
    @shoes = Shoe.all
  end

  # GET /shoes/1
  # GET /shoes/1.json
  def show
  end

  # GET /shoes/new
  def new
    @shoe = Shoe.new
  end

  # GET /shoes/1/edit
  def edit
  end

  # POST /shoes
  # POST /shoes.json
  def create
    @shoe = Shoe.new(shoe_params)

    respond_to do |format|
      if @shoe.save
        format.html { redirect_to @shoe, notice: 'Shoe was successfully created.' }
        format.json { render :show, status: :created, location: @shoe }
      else
        format.html { render :new }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shoes/1
  # PATCH/PUT /shoes/1.json
  def update
    respond_to do |format|
      if @shoe.update(shoe_params)
        format.html { redirect_to @shoe, notice: 'Shoe was successfully updated.' }
        format.json { render :show, status: :ok, location: @shoe }
      else
        format.html { render :edit }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoes/1
  # DELETE /shoes/1.json
  def destroy
    @shoe.destroy
    respond_to do |format|
      format.html { redirect_to shoes_url, notice: 'Shoe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shoe
      @shoe = Shoe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shoe_params
      params.require(:shoe).permit(:name, :style, :size, :color, :img_url, :src_url)
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @store = Store.first
    @items = []
    @items << Shoe.all
    @items << Shirt.all
    @items << Pant.all
    @items.flatten!
    @items.shuffle!
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pants_helper.rb
module PantsHelper
end

app/helpers/shirts_helper.rb
module ShirtsHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/application/_item.html.erb
<div class="three columns card textarea">
  <p class="item"><%= link_to item.src_url do %>
    <%= image_tag item.img_url, width: '200'%>
  <%end%></p>
  
  <p><% item.attributes.each do |attribute| %>
      <%=attribute.to_s.gsub("_", " ").capitalize%>: <%= item.send(attribute) %><br>
  <% end %></p>

  <%= link_to 'Show', item %>
</div>

app/views/application/_shoe.html.erb
<tr>
  <% item.attributes.each do |attribute| %>
    <td><%= item.send(attribute) %></td>
  <% end %>
  <td><%= link_to 'Show', item %></td>
</tr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Code4Reuse</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

<%= render partial: 'your-partial', layout: 'your-layout-partial' %>

app/views/pants/_pant.html.erb
  <div class="three columns card textarea">
    <p class="item"><%= link_to pant.src_url do %>
      <%= image_tag pant.img_url, height: '200'%>
      <%end%></p>
      <p><%= "name: "+ pant.name %>
        <%= link_to 'Show', pant %><br>
      <%= " style: " + pant.style %><br>
      <%= "inseam: " + pant.inseam.to_s %><br>
      <%= "waist: " + pant.waist.to_s %></p>
    </div>

app/views/pants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Inseam</th>
      <th>Waist</th>
      <th>Img url</th>
      <th>Src url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <%= render :partial => "application/item", :collection => @pants, :as => :item %>

  </tbody>
</table>

<br>

<%= link_to 'New Pant', new_pant_path %>

app/views/pants/new.html.erb
<h1>New Pant</h1>

<%= render 'form' %>

<%= link_to 'Back', pants_path %>

app/views/pants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pant.name %>
</p>

<p>
  <strong>style:</strong>
  <%= @pant.style %>
</p>

<p>
  <strong>Inseam:</strong>
  <%= @pant.inseam %>
</p>

<p>
  <strong>Waist:</strong>
  <%= @pant.waist %>
</p>

<p>
  <strong>Img url:</strong>
  <%= @pant.img_url %>
</p>

<p>
  <strong>Src url:</strong>
  <%= @pant.src_url %>
</p>

<%= link_to 'Edit', edit_pant_path(@pant) %> |
<%= link_to 'Back', pants_path %>

app/views/shirts/_shirt.html.erb
  <div class="three columns card textarea">
    <p class="item"><%= link_to shirt.src_url do %>
      <%= image_tag shirt.img_url, height: '200'%>
      <%end%></p>
      <p><%= "name: "+ shirt.name %>
        <%= link_to 'Show', shirt %><br>
      <%= " style: " + shirt.style %><br>
      <%= "size: " + shirt.size %><br>
      <%= "neck: " + shirt.neck.to_s %></p>
    </div>

app/views/shirts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shirts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Size</th>
      <th>Neck</th>
      <th>Img url</th>
      <th>Src url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <%= render :partial => "application/item", :collection => @shirts, :as => :item %>

  </tbody>
</table>

<br>

<%= link_to 'New Shirt', new_shirt_path %>

app/views/shirts/new.html.erb
<h1>New Shirt</h1>

<%= render 'form' %>

<%= link_to 'Back', shirts_path %>

app/views/shirts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shirt.name %>
</p>

<p>
  <strong>style:</strong>
  <%= @shirt.style %>
</p>

<p>
  <strong>Size:</strong>
  <%= @shirt.size %>
</p>

<p>
  <strong>Neck:</strong>
  <%= @shirt.neck %>
</p>

<p>
  <strong>Img url:</strong>
  <%= @shirt.img_url %>
</p>

<p>
  <strong>Src url:</strong>
  <%= @shirt.src_url %>
</p>

<%= link_to 'Edit', edit_shirt_path(@shirt) %> |
<%= link_to 'Back', shirts_path %>

app/views/shoes/_shoe.html.erb
<div class="three columns card textarea">
  <p class="item"><%= link_to shoe.src_url do %>
    <%= image_tag shoe.img_url, width: '200'%>
    <%end%></p>

    <p><%= "name: "+ shoe.name %>
    <%= link_to 'Show', shoe %><br>
    <%= " style: " + shoe.style %><br>
    <%= "color: " + shoe.color %><br>
    <%= "size: " + shoe.size.to_s %></p>
</div>

app/views/shoes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shoes</h1>

<table>

  <tbody>

    <% @shoes.each do |shoe| %>
      <%= render '/shoes/shoe', shoe: shoe %>
    <% end %>

    </tbody>
  </table>

<br>

app/views/shoes/new.html.erb
<h1>New Shoe</h1>

<%= render 'form' %>

<%= link_to 'Back', shoes_path %>

app/views/shoes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shoe.name %>
</p>

<p>
  <strong>style:</strong>
  <%= @shoe.style %>
</p>

<p>
  <strong>Size:</strong>
  <%= @shoe.size %>
</p>

<p>
  <strong>Color:</strong>
  <%= @shoe.color %>
</p>

<p>
  <strong>Img url:</strong>
  <%= @shoe.img_url %>
</p>

<p>
  <strong>Src url:</strong>
  <%= @shoe.src_url %>
</p>

<%= link_to 'Edit', edit_shoe_path(@shoe) %> |
<%= link_to 'Back', shoes_path %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1> <%= @store.name %> </h1>

<table>

  <tbody>

  <%= render @items %>

  </tbody>
</table>

<br>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>